### ISSUE TITLE
Convert yaml sensor config to websocket message command

### ISSUE THREAD

**Issue by nhancdt2602** [HPCMonitoring/sensor-manager-api#26]
This issue includes task which convert filter yaml expressions to postfix expression

**Comment by phucvinh57** [comment]
I've done these jobs:
- Convert yaml script to AST in JSON (aka lexer & parser phase)
- Validate parsed AST (aka static check phase)
- Write type `ConfigScriptAST` for AST

<https://github.com/HPCMonitoring/sensor-manager-api/blob/43bf287e1be845bdb77881ff272e2f977fefbe52/src/handlers/sensor.handler.ts#L101>

Use the AST to transpile to command which are sent to virtual sensor. A command should contains:
- `type`: Specifies which type of data that sensor send to kafka broker
- `fields`: List of properties sensor must collect
- `conditions`: Null if `type` is not `process`. It's a expression in prefix order (prefer postfix)

Format of command will depend on your choice @cudothanh-Nhan.
